# Generated by Django 2.0 on 2018-11-12 05:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20181110_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descriprion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
