# Generated by Django 2.0 on 2018-11-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20181112_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='metadescription',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
